### ISSUE TITLE
hass-aigues-barcelona evita que la integración nuki se cargue

### ISSUE THREAD

**Issue by cdeharo** [duhow/hass-aigues-barcelona#13]
Al instalar la integración hass-aigues-barcelona desde HACS, la integración nativa [Nuki](https://www.home-assistant.io/integrations/nuki) falla al cargar, registrando el siguiente error:
```
Logger: homeassistant.config_entries
Source: components/nuki/__init__.py:128
First occurred: 06:28:58 (1 occurrences)
Last logged: 06:28:58

Error setting up entry XXXXXXXX for nuki
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/nuki/__init__.py", line 129, in _create_webhook
    await hass.async_add_executor_job(
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nuki/__init__.py", line 210, in async_setup_entry
    await _create_webhook(hass, entry, bridge)
  File "/usr/src/homeassistant/homeassistant/components/nuki/__init__.py", line 128, in _create_webhook
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
TimeoutError
```

Tras desinstalar hass-aigues-barcelona, se arregla Nuki. No llegué a configurar esta integración debido a este problema.

Entorno:
* Home Assistant: *2023.6.3*
* HACS: *1.32.1*
* [hass-aigues-barcelona](https://github.com/duhow/hass-aigues-barcelona): 0.2.0

**Comment by duhow** [comment]
No hay ninguna mención a que el `custom_component` esté causando estos problemas, y en este caso mi integración tampoco crea webhooks.
Puedes escalar el problema en `home-assistant/core` ?
Configura también home assistant para tener logs en `debug` y poder proporcionar más información, sólo con esto es dificil identificar el problema.
